implemented getCategoryTranslation, getSectionTranslation and getArticleTranslation.
cloudbees-oss/zendesk-java-client pull request #545
Opened 2023-03-02 15:25 UTC by Walti91

added methods to fetch a single translation for a category, section or an article. as seen here https://developer.zendesk.com/api-reference/help_center/help-center-api/translations/#show-translation

2023-03-03 10:51 UTC, PierreBtz requested changes
Thanks for the contribution!

We need to sort out if the endpoint you are using for category and section exist.

We will also need to add some tests to cover the new method(s). I know that it's a bit hard to write those tests since external contributors don't have access to our Zendesk sandbox. In case you are not able to write those, I can do it for you when I have some time.

2023-03-03 10:51 UTC, PierreBtz commented on src/main/java/org/zendesk/client/v2/Zendesk.java
> +    public Translation getCategoryTranslation(long categoryId, String locale) {
I don't see any endpoint to show translations for Category, am I missing something?

2023-03-03 10:51 UTC, PierreBtz commented on src/main/java/org/zendesk/client/v2/Zendesk.java
> +    public Translation getArticleTranslation(long articleId, String locale) {
Shouldn't we use the same verb as the Zendesk API: https://developer.zendesk.com/api-reference/help_center/help-center-api/translations/#show-translation:

```suggestion
    public Translation showArticleTranslation(long articleId, String locale) {
```

2023-03-03 10:51 UTC, PierreBtz commented on src/main/java/org/zendesk/client/v2/Zendesk.java
> +    public Translation getSectionTranslation(long sectionId, String locale) {
I don't see any endpoint to show translations for Section either.

2023-03-03 12:45 UTC, Walti91 commented
Hi!

I renamed the methods to match the API documentation which is indeed missing the endpoints for categories and sections, but they do exist and are working. I also added tests for the new methods.

Kind regards

2023-03-03 13:33 UTC, PierreBtz commented
@Walti91 I opened a support ticket with Zendesk to understand why those APIs are not documented, we cannot really rely on them if the lack of documentation is on purpose and they are internal APIs for some reason. I'll keep you updated.

2023-03-06 08:49 UTC, PierreBtz approved these changes
Zendesk support confirmed there is a documentation issue on their end, so I think we can move in with this PR.
Thanks for the contribution.

2023-03-06 08:50 UTC, merged

2023-03-06 09:19 UTC, PierreBtz commented
Released: https://github.com/cloudbees-oss/zendesk-java-client/discussions/547