Support List Locales operation
cloudbees-oss/zendesk-java-client pull request #619
Opened 2023-09-12 22:50 UTC by topero

Hello,

We needed to support the [List Locales operation](https://developer.zendesk.com/api-reference/ticketing/account-configuration/locales/#list-locales) and this is the change that we implemented.

We tried to follow the contributing guidelines, but feel free to comment if we missed something, please.

2023-09-15 08:46 UTC, PierreBtz requested changes
@topero thanks for the addition. Change lgtm, I'd like to have a test to cover any change that might happen in the API in the future.

I know it's a pain to write a test for this library since we cannot grant access to our internal ZD testing instance to external contributors, so I can take care of the test if needed.

2023-09-22 22:27 UTC, topero commented
Sorry for the late reply, @PierreBtz.
A couple of unit tests have been added to the pull request.

In addition, a few more attributes have been added to the "Locale" class because they were returned by our Zendesk instance although I haven't found them in [Zendesk documentation](https://developer.zendesk.com/api-reference/ticketing/account-configuration/locales/#json-format).

2023-09-29 14:31 UTC, PierreBtz commented
@topero sorry I had a rather busy week, I'll look at the PR beginning of next week in more details but at the first glance it looks good.
My only reservation is that you are adding undocumented fields, I usually tend to open a ticket with Zendesk support to have them confirm they really exist and update their documentation before accepting such change.
If you need the fields, it's allright, we can do it but it will delay the merge of the PR. If you don't need them, I'd suggest to not put them, this will fast-track this.

2023-10-12 14:43 UTC, PierreBtz reviewed
lgtm once we sort out the fields that are not documented by Zendesk.

2023-10-12 14:43 UTC, PierreBtz commented on src/main/java/org/zendesk/client/v2/model/Locale.java
> +  private Boolean isDefault;
undocumented by ZD

2023-10-12 14:43 UTC, PierreBtz commented on src/main/java/org/zendesk/client/v2/model/Locale.java
> +  private String nativeName;
undocumented by ZD

2023-10-12 14:43 UTC, PierreBtz commented on src/main/java/org/zendesk/client/v2/model/Locale.java
> +  private String presentationName;
undocumented by ZD

2023-10-12 14:43 UTC, PierreBtz commented on src/main/java/org/zendesk/client/v2/model/Locale.java
> +  private Boolean rtl;
undocumented by ZD

2023-10-26 06:25 UTC, topero commented
I'm sorry for the very very long delay to answer you, @PierreBtz .

On 2 October, a Zendesk Technical Account Manager was reached out with regard to this topic. In my unicorn-and-rainbows world, the documentation is updated and this PR might be kept as it was. But the reality is that I've seen no answer so far. So the undocumented fields have been removed and the tests, adjusted.

Let me know if something else needs to be modified, please.

2023-11-06 09:02 UTC, PierreBtz approved these changes
Great! Thanks for the contribution!

2023-11-06 09:02 UTC, merged